# Generated by Django 3.1 on 2020-08-27 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0007_auto_20200826_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ManyToManyField(related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
