# Generated by Django 3.1 on 2020-08-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='user',
        ),
    ]
